### ISSUE TITLE
Rebuilding Protocol lockfile results in annotations

### ISSUE THREAD

**Issue by haydenbleasel** [bradlc/mdx-annotations#1]
Sorry that this is specific to the [Protocol template](https://protocol.tailwindui.com/), however it's the only use case I have for this issue.

Essentially what's happening is that with a fresh download of the Protocol template, the specific deps listed in the lockfile work perfectly. However, if the lockfile is rebuilt (or you switch to a different package manager), there's an issue with mdx-annotations where it can successfully identify annotations and apply the `annotation` prop, but it's can't replace them with actual properties later on.

I went into a messy deep dive [on Twitter](https://twitter.com/bradlc/status/1603799329726251009). Seeing as it's dependency version based, I'm guessing it's based on an upgrade to an underlying dependency not directly listed. The diff o the thread might help. In terms of actually fixing it, I think the answer might lie in the `recma` transformer. Happy to do more digging if it helps. I'd be curious to see what the answer is!

✌️

**Comment by bradlc** [comment]
Fixed in `v0.1.1` 👍
